name: whatsdev
version: '1.0.0'
summary: WhatsApp Web Desktop App for Linux
description: |
  WhatsDev is a lightweight, portable WhatsApp desktop client that runs on any Linux distribution.
  
  Features:
  - System Tray with minimize to tray
  - Unread message counter
  - Clean UI without menu bar clutter
  - Single instance mode
  - Performance modes (Normal/Low Resource)

grade: stable
confinement: strict
base: core22
compression: lzo

architectures:
  - build-on: amd64

apps:
  whatsdev:
    command: bin/whatsdev
    extensions: [gnome]
    plugs:
      - audio-playback
      - audio-record
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
    environment:
      DISABLE_WAYLAND: '1'
      GTK_USE_PORTAL: '1'

parts:
  whatsdev:
    plugin: dump
    source: https://github.com/riturajprofile/whatsdev/releases/latest/download/WhatsDev.AppImage
    source-type: file
    build-packages:
      - wget
    stage-packages:
      - libfuse2
      - libnspr4
      - libnss3
      - libxss1
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libcups2
      - libdrm2
      - libgbm1
      - libgtk-3-0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/WhatsDev.AppImage
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/whatsdev << 'EOF'
      #!/bin/bash
      cd $SNAP
      ./WhatsDev.AppImage --appimage-extract-and-run --no-sandbox "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/whatsdev

  desktop-entry:
    plugin: dump
    source: snap/gui
    organize:
      whatsdev.desktop: usr/share/applications/whatsdev.desktop
      icon.png: usr/share/icons/hicolor/256x256/apps/whatsdev.png
